[build-system]
requires = ["maturin>=1.0,<2.0", "setuptools", "setuptools-rust", "wheel"]
build-backend = "maturin"

[tool.maturin]
compatibility = "linux"
name = "alluxiocommon"
module-name = "alluxiocommon"
